[package]
name = "elixir-dydx-integration"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "schema"
path = "src/bin/schema.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-std = { version = "2.0.0", features = ["std", "cosmwasm_2_0"] }
cosmwasm-schema = { version = "2.0.0" }
cw-storage-plus = "2.0.0"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.61"
schemars = "0.8.21"
cw-utils = "2.0.0"

[dev-dependencies]
cw-multi-test = "2.0.0"